[opener]
edit = [
  { run = 'kitty nvim "$@"', desc = "nvim", block = true }
]
open = [
  { run = 'zathura "$@"',  desc = "zathura",  mime = "application/pdf" },
  { run = 'imv "$@"',      desc = "imv",       mime = "image/*" },
  { run = 'glow --pager "$@"', desc = "glow",  mime = "text/markdown" },
  { run = 'mpv "$@"',      desc = "mpv",       mime = "video/*" },
  { run = 'mpv "$@"',      desc = "mpv",       mime = "audio/*" },
  { run = 'nvim "$@"',     desc = "nvim",      mime = "text/*" },
]
[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'
[[plugin.prepend_previewers]]
url = "*.tar*"
run = 'piper --format=url -- tar tf "$1"'
