background {
    monitor =
    path = /usr/share/sddm/themes/sddm-astronaut-theme/Backgrounds/black_hole.png
    blur_passes = 1
    blur_size = 3
    brightness = 0.6
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(cdd6f4)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    placeholder_text = <i>Passwort...</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(cba6f7ff)
    font_size = 64
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d. %B %Y")"
    color = rgba(cdd6f4aa)
    font_size = 24
    position = 0, 30
    halign = center
    valign = center
}

label {
    monitor =
    text = Willkommen im Hyprland...
    color = rgba(cdd6f4aa)
    font_size = 24
    position = -730, 500 
    halign = center
    valign = center
}
