[addressbooks]
[[contacts]]
path = ~/.local/share/contacts/contacts/

[general]
default_action = list
editor = nvim
merge_editor = nvim

[contact table]
display = first_name
group_by_addressbook = false
reverse = false
show_nicknames = false
show_uids = false
sort = last_name

[vcard]
preferred_version = 3.0
search_in_source_files = false
skip_unparsable = false
